name: Test Activating Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: miterra-site-build
  cancel-in-progress: false

jobs:
  build:
    runs-on: macos-13
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Test Prince
      run: |
        export LC_CTYPE="en_US.UTF-8"
        export LC_ALL="en_US.UTF-8"
        brew install --cask prince
        prince --javascript ./build/miterra-docs/main/print.html -o ./build/print.pdf
        zip -qq -r pdf.zip ./build

    - name: Get next version
      uses: reecetech/version-increment@2024.10.1
      id: version
      with:
        scheme: calver

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false
        make_latest: true
        name: ${{ steps.version.outputs.v-version }}
        tag_name: ${{ steps.version.outputs.v-version }}
        body: |
          Release ${{ steps.version.outputs.v-version }} generated by GitHub Actions.
        files: ./pdf.zip
        fail_on_unmatched_files: true


  
