name: Test Activating Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: miterra-site-build
  cancel-in-progress: false

jobs:
  activate:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.head_commit.message, '[Release]')
    steps:
    - run: echo Activated

  build:
    needs: activate
    runs-on: ubuntu-latest
    
    steps:
    - name: Generate GitHub App installation access token (IAT)
      id: generate_iat
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.DOCS_APP_ID }}
        private-key: ${{ secrets.DOCS_APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
    
    - name: Set the token as environment variable
      run: echo "GIT_CREDENTIALS=https://x-access-token:${{ steps.generate_iat.outputs.token }}@github.com" >> "$GITHUB_ENV"

    - name: Get next version
      uses: reecetech/version-increment@2024.10.1
      id: version
      with:
        use_api: true
        scheme: calver
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: 'SSM-WEnR/workflow-private'
        ref: 'main'
        token: ${{steps.generate_iat.outputs.token}}
    
    - name: Output
      run: |
        echo "Release ${{ steps.version.outputs.prefixed-v-version }} generated by GitHub Actions."

