on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repo'
        required: true
        type: string
      source_owner:
        description: 'Source repo owner'
        required: true
        type: string
      source_message:
        description: 'Source message'
        required: true
        type: string

permissions:
  contents: read

concurrency:
  group: miterra-site-build
  cancel-in-progress: false

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Generate release message
      id: generate_message
      run: |
        echo "datetime=$(date +'%Y-%m-%dT%H:%M:%S%z')" >> $GITHUB_ENV

        if [[ '${{ github.event_name }}' == 'workflow_dispatch' ]]; then
          echo "trigger_msg=Triggered from ${{github.event.inputs.source_repo}} by ${{github.event.inputs.source_owner}}." >> $GITHUB_OUTPUT
          echo "commit_msg=${{github.event.inputs.source_message}}" >> $GITHUB_OUTPUT
        else
          echo "trigger_msg=Triggered by ${{github.event_name}} event." >> $GITHUB_OUTPUT
          echo "commit_msg=${{github.event.head_commit.message}}" >> $GITHUB_OUTPUT
        fi
    
    - name: Generate GitHub App installation access token (IAT)
      id: generate_iat
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.DOCS_APP_ID }}
        private-key: ${{ secrets.DOCS_APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
    
    - name: Set the token as environment variable
      run: echo "GIT_CREDENTIALS=https://x-access-token:${{ steps.generate_iat.outputs.token }}@github.com" >> "$GITHUB_ENV"

    - name: Get next version
      uses: reecetech/version-increment@2024.10.1
      id: version
      with:
        use_api: true
        scheme: calver
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: 'SSM-WEnR/workflow-private'
        ref: 'main'
        token: ${{steps.generate_iat.outputs.token}}
    
    - name: Output
      run: |
        echo "${{ steps.generate_message.outputs.trigger_msg }}"
        echo "Release ${{ steps.version.outputs.prefixed-v-version }} generated by GitHub Actions on ${{ env.datetime }}."
        echo "Commit message: ${{ steps.generate_message.outputs.commit_msg }}"
