name: Test Versioning
on:
  push:
    branches: [main]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get next version
      uses: reecetech/version-increment@2024.10.1
      id: version
      with:
        use_api: true
        scheme: calver
        tag_prefix: Release_

    - name: Check version
      run: |
        echo "version=${{ steps.version.outputs.version }}"
        echo "v-version=${{ steps.version.outputs.v-version }}"
        echo "prefixed-v-version=${{ steps.version.outputs.prefixed-v-version }}"
        echo "datetime=$(date +'%Y-%m-%dT%H:%M:%S%z')"
        echo "Commit message: ${{ github.event.head_commit.message }}"
    
